replicas: 1

port: 11443

annotations:
  cert-manager.io/cluster-issuer: letsencrypt
  nginx.ingress.kubernetes.io/proxy-body-size: 200m
  nginx.ingress.kubernetes.io/proxy_read_timeout: "1800"


startupProbe:
  httpGet:
    scheme: HTTP
    path: /health?whoami=amazon
    port: 11443
  initialDelaySeconds: 5
  timeoutSeconds: 5
  failureThreshold: 60
  periodSeconds: 5

readinessProbe:
  httpGet:
    scheme: HTTP
    path: /health?whoami=amazon
    port: 11443
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 10

image:
  prod: pickrelated/app-sample-back
  staging: pickrelated/app-sample-back-staging
  dev: pickrelated/app-sample-back-dev

host:
  prod: api.app-sample.pickrelated.com
  staging: api.app-sample.staging.pickrelated.com
  dev: api.app-sample.dev.pickrelated.com

secretName:
  prod: tls-pickrelated-wildcard
  staging: tls-back
  dev: tls-back
