replicas: 1

port: 80

annotations:
  cert-manager.io/cluster-issuer: letsencrypt
  nginx.ingress.kubernetes.io/configuration-snippet: |
    more_set_headers "X-Frame-Options: DENY";

startupProbe:
  httpGet:
    scheme: HTTP
    path: /
    port: 80
  initialDelaySeconds: 5
  timeoutSeconds: 5
  failureThreshold: 60
  periodSeconds: 5

readinessProbe:
  httpGet:
    scheme: HTTP
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 30

image:
  prod: pickrelated/app-sample-front
  staging: pickrelated/app-sample-front-staging
  dev: pickrelated/app-sample-front-dev

host:
  prod: app-sample.pickrelated.com
  staging: app-sample.staging.pickrelated.com
  dev: app-sample.dev.pickrelated.com

secretName:
  prod: tls-pickrelated-wildcard
  staging: tls-front
  dev: tls-front
